import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Main } from '../styles/index'
import DefaultButton from '@/components/DefaultButton'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hypesoft | Desafio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpeg" />
      </Head>
      <Main className={inter.className}>
        <h1>Hello World!</h1>
      </Main>
    </>
  )
}
