import Head from 'next/head'
import { Footer, MainSectionsWrapper } from '../styles/index'
import { PresentationSection } from '../components/sections/PresentationSection'
import { AboutSection } from '../components/sections/AboutSection'
import { MyServiceSection } from '../components/sections/MyServiceSection'
import { MySelectedWorkSection } from '../components/sections/MySelectedWorkSection'
import { CompaniesIveWorked } from '../components/sections/CompaniesIveWorked'
import { CallToActionSection } from '../components/sections/CallToActionSection'
import { ContactSection } from '../components/sections/ContactSection'

import Image from 'next/image'
import { TestimonialsSection } from '../components/sections/TestimonialsSection'
import { useContext } from 'react'
import { TranslationContext } from '@/context/TranslationContext'
import { MainHeader } from '../components/MainHeader'

export default function Home() {
  const { madeWith, byGuilhermeAnd } = useContext(TranslationContext)

  return (
    <>
      <Head>
        <title>Hypesoft | Desafio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpeg" />
      </Head>
      <main>
        <MainHeader />
        <PresentationSection />
        <MainSectionsWrapper>
          <AboutSection />
          <MyServiceSection />
          <MySelectedWorkSection />
          <CompaniesIveWorked />
          <CallToActionSection />
          <TestimonialsSection />
          <ContactSection />
        </MainSectionsWrapper>
        <Footer id="mainFooter" data-testid="mainFooter">
          <Image
            title="HypesoftLogo-Footer"
            src={'/HypesoftLogo.png'}
            alt={''}
            width={253}
            height={59}
          />
          <span>
            {madeWith} <strong className="CreditsHeart">♥</strong>{' '}
            {byGuilhermeAnd} <strong>Hypesoft</strong>
          </span>
        </Footer>
      </main>
    </>
  )
}
